on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - run: npm install
      - run: npm run lint
      - run: npm run typecheck
      - name: Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
